services:

  postgres:
    image: postgres:13
    container_name: db-postgres
    env_file: 
      - ./postgres/.env.postgres
    ports:
      - 5433:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      rede:
        ipv4_address: 192.168.10.5

  backend-api:
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
    container_name: backend-api
    depends_on:
      - postgres
    command: npm run start
    ports:
      - 3000:3000
    networks:
      rede:
        ipv4_address: 192.168.10.2

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    container_name: frontend
    depends_on:
      - backend-api
    ports:
      - 8080:80
    networks:
      rede:
        ipv4_address: 192.168.10.3

networks:
  rede:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.10.0/24

volumes:
  postgres-data: