# Usar a imagem base do Node.js com Alpine LTS
FROM node:lts-alpine

# Definir o diretório de trabalho no contêiner
WORKDIR /app

# Copiar o arquivo package.json e package-lock.json (se disponível) para o diretório de trabalho
COPY package*.json ./

# Instalar as dependências do projeto
RUN npm install

# Copiar os arquivos restantes do projeto para o diretório de trabalho
COPY . .

# Comando para rodar a aplicação
#CMD ["node", "src/app.js"]
